version: '2'
services:
  zeus-postgresql:
    image: postgres:11.5
    # volumes:
    #     - ~/volumes/jhipster/Zeus/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=Zeus
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
